[package]
name = "Mouse-Spacer"
version = "0.1.0"
edition = "2021"

[dependencies]
enigo = "0.3.0"
nokhwa = "0.10.7"
numpy = "0.23.0"
opencv = {version = "0.94.1", features = ["buildtime-bindgen"] }
pyo3 = "0.23.4"
tch = "0.18.1"

